name: CICerts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libsqlite3-dev
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.x"
          channel: "stable"
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed lib
      - run: flutter packages pub run build_runner build
      - run: flutter analyze --pub
      #- run: flutter test --coverage
      #- uses: codecov/codecov-action@v1
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    file: ./coverage/lcov.info
      - run: flutter build apk --flavor prod --no-shrink
      - uses: actions/upload-artifact@v1
        with:
          name: photoprism-apk
          path: build/app/outputs/apk/prod/release/
